org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.configureondemand=true
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
app.versionName=1.0.8
app.versionCode=26
